export class UsersService {

    users = [{
        firstname:'Jack',
        surname:'White',
        day:'9',
        month:'July',
        year:'1975',
        gender:'Male',
        pronoun:'',
        customGender:'',
        email:'jackIII@gmail.com',
        password:'thirdman',
        birthplace:'Detroit, USA',
        work:'Owner and Founder of Third Man Records',
        school:'Cass Technichal High School',
        university:'',
        currentCity:'Nashville, USA',
        relationship:'Divorced',
        about:"I really don't like to take the easy way out, if I can help it, on anything I do, I like to really make it a challenge. I don't know how to create by taking the easy routes. I've tried, you know, I've tried to let myself, but I always struggle to compensate.",
        friends:[],
        request: false,
        isFriend: false
        }, {
        firstname:'Alanis',
        surname:'Morissette',
        day:'1',
        month:'June',
        year:'1974',
        gender:'Female',
        pronoun:'',
        customGender:'',
        email:'alanis1974@gmail.com',
        password:'am0106',
        birthplace:'Ottawa, Canada',
        work:'Singer - Songwriter',
        school:'Glebe Collegiate Institute',
        university:'',
        currentCity:'Los Angeles, USA',
        relationship:'Married',
        about:"I want to walk through life instead of being dragged through it.",
        friends:[],
        request: false,
        isFriend: false
        }, {
        firstname:'Thom',
        surname:'Yorke',
        day:'7',
        month:'October',
        year:'1968',
        gender:'Male',
        pronoun:'',
        customGender:'',
        email:'thommyboy@hotmail.com',
        password:'radioyorke',
        birthplace:'Wellingborough, England',
        work:'Musician',
        school:'Abingdon School, Oxfordshire',
        university:'University of Exeter',
        currentCity:'Oxfordshire, England',
        relationship:'Married',
        about:'I believe that any great work of art is, in itself, a form of resistance against a sense of powerlessness.',
        friends:[],
        request: true,
        isFriend: false        
        },{
        firstname:'Lady',
        surname:'Gaga',
        day:'28',
        month:'March',
        year:'1986',
        gender:'Female',
        pronoun:'',
        customGender:'',
        email:'bornthisway@gmail.com',
        password:'gaga1986',
        birthplace:'New York, USA',
        work:'Singer - Songwriter',
        school:'Convent of the Sacred Heart',
        university:'New York University Tisch School of the Arts',
        currentCity:'Malibu, USA',
        relationship:'In a relationship',
        about:'Fight and push harder for what you believe in, you’d be surprised, you are much stronger than you think.',
        friends:[],
        request: true,
        isFriend: false
        },{
        firstname:'Paul',
        surname:'McCartney',
        day:'18',
        month:'June',
        year:'1942',
        gender:'Male',
        pronoun:'',
        customGender:'',
        email:'macca@hotmail.com',
        password:'sirpaul1942',
        birthplace:'Liverpool, England',
        work:'Musician - Songwriter',
        school:'Liverpool Institute High School for Boys',
        university:'',
        currentCity:'London, England',
        relationship:'Married',
        about:"I'm not religious, but I'm very spiritual.",
        friends:[],
        request: true,
        isFriend: false
        }];
}
