export class UsersService {

    users = [{
        firstname: 'Jack',
        surname: 'White',
        day: '9',
        month: 'July',
        year: '1975',
        gender: 'Male',
        pronoun: '',
        customGender: '',
        email: 'jackIII@gmail.com',
        password: 'thirdman',
        birthplace: 'Detroit, USA',
        work: 'Owner and Founder of Third Man Records',
        school: 'Cass Technichal High School',
        currentCity: 'Nashville, USA',
        relationship: 'Divorced',
        about: "I really don't like to take the easy way out, if I can help it, on anything I do, I like to really make it a challenge. I don't know how to create by taking the easy routes. I've tried, you know, I've tried to let myself, but I always struggle to compensate.",
        friends: [],
        request: false,
        isFriend: false
    }, {
        firstname: 'Alanis',
        surname: 'Morissette',
        day: '1',
        month: 'June',
        year: '1974',
        gender: 'Female',
        pronoun: '',
        customGender: '',
        email: 'alanis1974@gmail.com',
        password: 'am0106',
        birthplace: 'Ottawa, Canada',
        work: 'Singer - Songwriter',
        school: 'Glebe Collegiate Institute',
        currentCity: 'Los Angeles, USA',
        relationship: 'Married',
        about: "I want to walk through life instead of being dragged through it.",
        friends: [],
        request: false,
        isFriend: false
    }, {
        firstname: 'Thom',
        surname: 'Yorke',
        day: '7',
        month: 'October',
        year: '1968',
        gender: 'Male',
        pronoun: '',
        customGender: '',
        email: 'thommyboy@hotmail.com',
        password: 'radioyorke',
        birthplace: 'Wellingborough, England',
        work: 'Musician',
        school: 'Abingdon School, Oxfordshire',
        currentCity: 'Oxfordshire, England',
        relationship: 'Married',
        about: 'I believe that any great work of art is, in itself, a form of resistance against a sense of powerlessness.',
        friends: [],
        request: true,
        isFriend: false
    }, {
        firstname: 'Lady',
        surname: 'Gaga',
        day: '28',
        month: 'March',
        year: '1986',
        gender: 'Female',
        pronoun: '',
        customGender: '',
        email: 'bornthisway@gmail.com',
        password: 'gaga1986',
        birthplace: 'New York, USA',
        work: 'Singer - Songwriter',
        school: 'Convent of the Sacred Heart',
        currentCity: 'Malibu, USA',
        relationship: 'In a relationship',
        about: 'Fight and push harder for what you believe in, you’d be surprised, you are much stronger than you think.',
        friends: [],
        request: true,
        isFriend: false
    }, {
        firstname: 'Paul',
        surname: 'McCartney',
        day: '18',
        month: 'June',
        year: '1942',
        gender: 'Male',
        pronoun: '',
        customGender: '',
        email: 'macca@hotmail.com',
        password: 'sirpaul1942',
        birthplace: 'Liverpool, England',
        work: 'Musician - Songwriter',
        school: 'Liverpool Institute High School for Boys',
        currentCity: 'London, England',
        relationship: 'Married',
        about: "I'm not religious, but I'm very spiritual.",
        friends: [],
        request: true,
        isFriend: false
    }, {
        firstname: 'Alex',
        surname: 'Turner',
        day:'6',
        month:'January',
        year:'1986',
        gender:'Male',
        pronoun:'',
        customGender:'',
        email:'alexturner@gmail.com',
        password:'thirdman',
        birthplace:'Sheffield, England',
        work:'Lead singer at Arctic Monkeys',
        school:'Stocksbridge High School',
        currentCity:'London',
        relationship:'Single',
        about:"Whatever people say I am, that's what I'm not.",
        friends:[],
        request: false,
        isFriend: false
    }, {
        firstname: 'Stevie',
        surname: 'Wonder',
        day:'13',
        month:'May',
        year:'1950',
        gender:'Male',
        pronoun:'',
        customGender:'',
        email:'stevie@gmail.com',
        password:'thirdman',
        birthplace:'Saginaw, Michigan, United States',
        work:'Singer, Pianist, Songwriter',
        school:'Fitzgerald Elementary School',
        currentCity:'Los Angeles, California',
        relationship:'Married',
        about:"Just because a man lacks the use of his eyes doesn't mean he lacks vision.",
        friends:[],
        request: false,
        isFriend: false
    }, {
        firstname: 'Norah',
        surname: 'Jones',
        day:'30',
        month:'March',
        year:'1979',
        gender:'Female',
        pronoun:'',
        customGender:'',
        email:'n.jones@gmail.com',
        password:'norah',
        birthplace:'Manhattan, New York',
        work:'Singer, Pianist, Songwriter',
        school:'University of North Texas',
        currentCity:'New York City',
        relationship:'Married',
        about:"I genuinely don't feel that anything that's been written or said about me has overshadowed my music, and that's the most important thing as far as I'm concerned.",
        friends:[],
        request: false,
        isFriend: false
    }, {
        firstname: 'KT',
        surname: 'Tunstall',
        day:'23',
        month:'june',
        year:'1975',
        gender:'Female',
        pronoun:'',
        customGender:'',
        email:'tunstall@gmail.com',
        password:'tunst.kt',
        birthplace:'Edinburgh, Scottland',
        work:'Singer, Songwriter',
        school:'Madras College',
        currentCity:'London',
        relationship:'Divorced',
        about:"British music lovers in general are dreadfully concerned about being cool, but I'm quite happy to grab uncool by the horns at any opportunity.",
        friends:[],
        request: false,
        isFriend: false
    }, {
        firstname: 'Jack',
        surname: 'Johnson',
        day:'18',
        month:'May',
        year:'1975',
        gender:'Male',
        pronoun:'',
        customGender:'',
        email:'jackj@gmail.com',
        password:'ocean',
        birthplace:'Oahu, Hawaii',
        work:'Singer, Songwriter',
        school:'University of California',
        currentCity:'Oahu, Hawaii',
        relationship:'Married',
        about:"We've got everything we need right here, and everything we need is enough.",
        friends:[],
        request: false,
        isFriend: false
    }, {
        firstname: 'Damon',
        surname: 'Albarn',
        day: '23',
        month: 'March',
        year: '1968',
        gender: 'Male',
        pronoun: '',
        customGender: '',
        email: 'damonalbarn@gmail.com',
        password: 'gorilla',
        birthplace: 'London, UK',
        work: 'Singer, songwriter, producer',
        school: 'Goldsmiths, University of London',
        currentCity: 'London, UK',
        relationship: 'Married',
        about: "As a musician usually music is your way out.",
        friends: [],
        request: false,
        isFriend: false
    }, {
        firstname: 'Laura',
        surname: 'Pergolizzi',
        day: '18',
        month: 'March',
        year: '1981',
        gender: 'Custom',
        pronoun: '',
        customGender: 'Neutral',
        email: 'lp@gmail.com',
        password: 'lostonyou',
        birthplace: 'Long Island, New York, USA',
        work: 'Singer, songwriter',
        school: 'Walt Whitman Institute',
        currentCity: 'New York, USA',
        relationship: 'Single',
        about: "I'm very accepting of how people live their lives.",
        friends: [],
        request: false,
        isFriend: false
    }, {
        firstname: 'Tash',
        surname: 'Sultana',
        day: '15',
        month: 'June',
        year: '1995',
        gender: 'Custom',
        pronoun: '',
        customGender: 'Non-binary',
        email: 'tashsul@gmail.com',
        password: 'sultana',
        birthplace: 'Melbourne, Australia',
        work: 'Singer, songwriter',
        school: 'The streets',
        currentCity: 'Melbourne, Australia',
        relationship: 'Engaged',
        about: "Music is the embodiment of my soul. When I play, I'm not performing a song: I'm becoming it.",
        friends: [],
        request: false,
        isFriend: false
    }, {
        firstname: 'Mac',
        surname: 'DeMarco',
        day: '30',
        month: 'April',
        year: '1990',
        gender: 'Male',
        pronoun: '',
        customGender: '',
        email: 'macdemarco@gmail.com',
        password: 'macdemac',
        birthplace: 'Duncan, British Columbia, Canada',
        work: 'Singer-songwriter',
        school: 'Strathcona High School',
        currentCity: 'Los Angeles, USA',
        relationship: 'In a relationship',
        about: "I'm going to try to do music for the rest of my life, but that's just trying. Maybe it's not going to work out. Who knows?",
        friends: [],
        request: false,
        isFriend: false
    }, {
        firstname: 'Alicia',
        surname: 'Keys',
        day: '25',
        month: 'January',
        year: '1981',
        gender: 'Female',
        pronoun: '',
        customGender: '',
        email: 'aliciak@gmail.com',
        password: 'alikeys',
        birthplace: 'New York City, USA',
        work: 'Singer-songwriter',
        school: 'Professional Performing Arts School',
        currentCity: 'Nashville, USA',
        relationship: 'Divorced',
        about: "Simplicity makes me happy.",
        friends: [],
        request: false,
        isFriend: false
    },];
}
